// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mpb.proto

package mpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求结果通知
type GM_Common struct {
	Result               *int32   `protobuf:"varint,1,req,name=Result" json:"Result,omitempty"`
	Params               []string `protobuf:"bytes,2,rep,name=Params" json:"Params"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GM_Common) Reset()         { *m = GM_Common{} }
func (m *GM_Common) String() string { return proto.CompactTextString(m) }
func (*GM_Common) ProtoMessage()    {}
func (*GM_Common) Descriptor() ([]byte, []int) {
	return fileDescriptor_31451f508f61938d, []int{0}
}

func (m *GM_Common) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GM_Common.Unmarshal(m, b)
}
func (m *GM_Common) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GM_Common.Marshal(b, m, deterministic)
}
func (m *GM_Common) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GM_Common.Merge(m, src)
}
func (m *GM_Common) XXX_Size() int {
	return xxx_messageInfo_GM_Common.Size(m)
}
func (m *GM_Common) XXX_DiscardUnknown() {
	xxx_messageInfo_GM_Common.DiscardUnknown(m)
}

var xxx_messageInfo_GM_Common proto.InternalMessageInfo

func (m *GM_Common) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *GM_Common) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

// 请求登录
type GM_LoginReq struct {
	Account              *string  `protobuf:"bytes,1,req,name=Account" json:"Account,omitempty"`
	Password             *string  `protobuf:"bytes,2,req,name=Password" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GM_LoginReq) Reset()         { *m = GM_LoginReq{} }
func (m *GM_LoginReq) String() string { return proto.CompactTextString(m) }
func (*GM_LoginReq) ProtoMessage()    {}
func (*GM_LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_31451f508f61938d, []int{1}
}

func (m *GM_LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GM_LoginReq.Unmarshal(m, b)
}
func (m *GM_LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GM_LoginReq.Marshal(b, m, deterministic)
}
func (m *GM_LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GM_LoginReq.Merge(m, src)
}
func (m *GM_LoginReq) XXX_Size() int {
	return xxx_messageInfo_GM_LoginReq.Size(m)
}
func (m *GM_LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GM_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_GM_LoginReq proto.InternalMessageInfo

func (m *GM_LoginReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *GM_LoginReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

// 响应登录
type GM_LoginResp struct {
	ID                   *int32   `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Status               *int32   `protobuf:"varint,2,opt,name=Status" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GM_LoginResp) Reset()         { *m = GM_LoginResp{} }
func (m *GM_LoginResp) String() string { return proto.CompactTextString(m) }
func (*GM_LoginResp) ProtoMessage()    {}
func (*GM_LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_31451f508f61938d, []int{2}
}

func (m *GM_LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GM_LoginResp.Unmarshal(m, b)
}
func (m *GM_LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GM_LoginResp.Marshal(b, m, deterministic)
}
func (m *GM_LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GM_LoginResp.Merge(m, src)
}
func (m *GM_LoginResp) XXX_Size() int {
	return xxx_messageInfo_GM_LoginResp.Size(m)
}
func (m *GM_LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GM_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_GM_LoginResp proto.InternalMessageInfo

func (m *GM_LoginResp) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *GM_LoginResp) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*GM_Common)(nil), "mpb.GM_Common")
	proto.RegisterType((*GM_LoginReq)(nil), "mpb.GM_LoginReq")
	proto.RegisterType((*GM_LoginResp)(nil), "mpb.GM_LoginResp")
}

func init() { proto.RegisterFile("mpb.proto", fileDescriptor_31451f508f61938d) }

var fileDescriptor_31451f508f61938d = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x48, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x48, 0x52, 0xd2, 0xe6, 0xe2, 0x74, 0xf7,
	0x8d, 0x77, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x13, 0xe2, 0xe3, 0x62, 0x0b, 0x4a, 0x2d, 0x2e, 0xcd,
	0x29, 0x91, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x05, 0xf1, 0x03, 0x12, 0x8b, 0x12, 0x73, 0x8b, 0x25,
	0x98, 0x14, 0x98, 0x35, 0x38, 0x95, 0x0c, 0xb8, 0xb8, 0xdd, 0x7d, 0xe3, 0x7d, 0xf2, 0xd3, 0x33,
	0xf3, 0x82, 0x52, 0x0b, 0x85, 0xf8, 0xb9, 0xd8, 0x1d, 0x93, 0x93, 0xf3, 0x4b, 0xf3, 0x20, 0xea,
	0x39, 0x85, 0x04, 0xb8, 0x38, 0x02, 0x12, 0x8b, 0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0x24, 0x98, 0x40,
	0x22, 0x4a, 0x5a, 0x5c, 0x3c, 0x08, 0x1d, 0xc5, 0x05, 0x42, 0x5c, 0x5c, 0x4c, 0x9e, 0x2e, 0x08,
	0xd3, 0x83, 0x4b, 0x12, 0x4b, 0x4a, 0x41, 0xa6, 0x33, 0x6a, 0xb0, 0x02, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xfc, 0x91, 0x60, 0x23, 0x9b, 0x00, 0x00, 0x00,
}

