//-- Auto generated by gproto --//
//--        DO NOT EDIT       --//
package protocol

import (
	"reflect"
	"strconv"
)

var EID _EID
var EIDIS map[int]string = make(map[int]string)
var EIDSI map[string]int = make(map[string]int)

func init() {
	enums := make([][]interface{}, 0)
	enums = append(enums, []interface{}{
		reflect.TypeOf(EID),
		reflect.ValueOf(&EID).Elem(),
		EIDIS,
		EIDSI,
	})
	for _, enum := range enums {
		ttpe := enum[0].(reflect.Type)
		vtpe := enum[1].(reflect.Value)
		len := ttpe.NumField()
		for i := 0; i < len; i++ {
			tfld := ttpe.Field(i)
			vfld := vtpe.Field(i)
			sid := tfld.Tag.Get("id")
			id, _ := strconv.Atoi(sid)
			vfld.SetInt(int64(id))
			name := tfld.Tag.Get("name")
			enum[2].(map[int]string)[id] = name
			enum[3].(map[string]int)[name] = id
		}
	}
}

type EIDEnum int

type _EID struct {
	GM_HEART_BEAT            EIDEnum `id:"0" name:"GM_HEART_BEAT" to:"gate"`                  // 心跳包
	GM_KICK_OFF              EIDEnum `id:"1" name:"GM_KICK_OFF" to:"client"`                  // 下线
	GM_LOGIN_REQUEST         EIDEnum `id:"2" name:"GM_LOGIN_REQUEST" to:"hall" go:"0" rw:"1"` // 请求设备登录
	GM_LOGIN_RESPONSE        EIDEnum `id:"3" name:"GM_LOGIN_RESPONSE" to:"client"`            // 返回设备登录
	RPC_GET_ONLINE_FROM_GATE EIDEnum `id:"4" name:"RPC_GET_ONLINE_FROM_GATE" go:"0" rw:"1"`   // 从网关中获取在线玩家
	RPC_GATE_NOTIFY_OFFLINE  EIDEnum `id:"5" name:"RPC_GATE_NOTIFY_OFFLINE" go:"0" rw:"1"`    // 网关RPC玩家离线
}
