// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RPC_GateNotifyOfflineReq struct {
	UID                  *int32   `protobuf:"varint,1,req,name=UID" json:"UID,omitempty"`
	Url                  *string  `protobuf:"bytes,2,req,name=Url" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPC_GateNotifyOfflineReq) Reset()         { *m = RPC_GateNotifyOfflineReq{} }
func (m *RPC_GateNotifyOfflineReq) String() string { return proto.CompactTextString(m) }
func (*RPC_GateNotifyOfflineReq) ProtoMessage()    {}
func (*RPC_GateNotifyOfflineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *RPC_GateNotifyOfflineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPC_GateNotifyOfflineReq.Unmarshal(m, b)
}
func (m *RPC_GateNotifyOfflineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPC_GateNotifyOfflineReq.Marshal(b, m, deterministic)
}
func (m *RPC_GateNotifyOfflineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPC_GateNotifyOfflineReq.Merge(m, src)
}
func (m *RPC_GateNotifyOfflineReq) XXX_Size() int {
	return xxx_messageInfo_RPC_GateNotifyOfflineReq.Size(m)
}
func (m *RPC_GateNotifyOfflineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RPC_GateNotifyOfflineReq.DiscardUnknown(m)
}

var xxx_messageInfo_RPC_GateNotifyOfflineReq proto.InternalMessageInfo

func (m *RPC_GateNotifyOfflineReq) GetUID() int32 {
	if m != nil && m.UID != nil {
		return *m.UID
	}
	return 0
}

func (m *RPC_GateNotifyOfflineReq) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

type RPC_GetOnlineFromGateResp struct {
	ID                   []int32  `protobuf:"varint,1,rep,name=ID" json:"ID,omitempty"`
	Url                  []string `protobuf:"bytes,2,rep,name=Url" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPC_GetOnlineFromGateResp) Reset()         { *m = RPC_GetOnlineFromGateResp{} }
func (m *RPC_GetOnlineFromGateResp) String() string { return proto.CompactTextString(m) }
func (*RPC_GetOnlineFromGateResp) ProtoMessage()    {}
func (*RPC_GetOnlineFromGateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *RPC_GetOnlineFromGateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPC_GetOnlineFromGateResp.Unmarshal(m, b)
}
func (m *RPC_GetOnlineFromGateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPC_GetOnlineFromGateResp.Marshal(b, m, deterministic)
}
func (m *RPC_GetOnlineFromGateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPC_GetOnlineFromGateResp.Merge(m, src)
}
func (m *RPC_GetOnlineFromGateResp) XXX_Size() int {
	return xxx_messageInfo_RPC_GetOnlineFromGateResp.Size(m)
}
func (m *RPC_GetOnlineFromGateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RPC_GetOnlineFromGateResp.DiscardUnknown(m)
}

var xxx_messageInfo_RPC_GetOnlineFromGateResp proto.InternalMessageInfo

func (m *RPC_GetOnlineFromGateResp) GetID() []int32 {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *RPC_GetOnlineFromGateResp) GetUrl() []string {
	if m != nil {
		return m.Url
	}
	return nil
}

func init() {
	proto.RegisterType((*RPC_GateNotifyOfflineReq)(nil), "protocol.RPC_GateNotifyOfflineReq")
	proto.RegisterType((*RPC_GetOnlineFromGateResp)(nil), "protocol.RPC_GetOnlineFromGateResp")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2a, 0x48, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x26, 0x5c, 0x12,
	0x41, 0x01, 0xce, 0xf1, 0xee, 0x89, 0x25, 0xa9, 0x7e, 0xf9, 0x25, 0x99, 0x69, 0x95, 0xfe, 0x69,
	0x69, 0x39, 0x99, 0x79, 0xa9, 0x41, 0xa9, 0x85, 0x42, 0xdc, 0x5c, 0xcc, 0xa1, 0x9e, 0x2e, 0x12,
	0x8c, 0x0a, 0x4c, 0x1a, 0xac, 0x60, 0x4e, 0x51, 0x8e, 0x04, 0x93, 0x02, 0x93, 0x06, 0xa7, 0x92,
	0x09, 0x97, 0x24, 0x58, 0x57, 0x6a, 0x89, 0x7f, 0x1e, 0x48, 0xb5, 0x5b, 0x51, 0x7e, 0x2e, 0xc8,
	0x88, 0xa0, 0xd4, 0xe2, 0x02, 0x21, 0x2e, 0x2e, 0x26, 0xb0, 0x2e, 0x66, 0x64, 0x5d, 0xcc, 0x1a,
	0x9c, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0xe8, 0x21, 0x92, 0x81, 0x00, 0x00, 0x00,
}
