//go:binary-only-package
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frame.proto
package xmsg

import (
	_ "fmt"
	_ "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
// please upgrade the proto package
type FrameType int32

const (
	FrameType_LOOP_REQ FrameType = 1
	FrameType_MSG_REQ  FrameType = 2
	FrameType_RPC_REQ  FrameType = 3
	FrameType_RPC_RESP FrameType = 4
	FrameType_CGI_REQ  FrameType = 5
	FrameType_CGI_RESP FrameType = 6
)

var FrameType_name = map[int32]string{
	1: "LOOP_REQ",
	2: "MSG_REQ",
	3: "RPC_REQ",
	4: "RPC_RESP",
	5: "CGI_REQ",
	6: "CGI_RESP",
}
var FrameType_value = map[string]int32{
	"LOOP_REQ": 1,
	"MSG_REQ":  2,
	"RPC_REQ":  3,
	"RPC_RESP": 4,
	"CGI_REQ":  5,
	"CGI_RESP": 6,
}

func (x FrameType) Enum() *FrameType {
	return nil
}
func (x FrameType) String() string {
	return ""
}
func (x *FrameType) UnmarshalJSON(data []byte) error {
	return nil
}
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return []byte{}, []int{}
}

// 帧路由（请不要保持对其的引用，随时可能被重置）
type Route struct {
	// 源地址
	Src *string `protobuf:"bytes,1,req,name=Src" json:"Src,omitempty"`
	// 目标地址
	Dst *string `protobuf:"bytes,2,req,name=Dst" json:"Dst,omitempty"`
	// 路由ID
	RID *int32 `protobuf:"varint,3,req,name=RID" json:"RID,omitempty"`
	// 自增ID
	IID *int64 `protobuf:"varint,4,opt,name=IID" json:"IID,omitempty"`
	// 进程ID
	PID *int32 `protobuf:"varint,5,opt,name=PID" json:"PID,omitempty"`
	// 协程ID
	GID *int32 `protobuf:"varint,6,opt,name=GID,def=-1" json:"GID,omitempty"`
	// 用户ID
	UID *int32 `protobuf:"varint,7,opt,name=UID,def=-1" json:"UID,omitempty"`
	// reserved ID1
	MID1 *int64 `protobuf:"varint,8,opt,name=MID1,def=-1" json:"MID1,omitempty"`
	// reserved ID2
	MID2 *int64 `protobuf:"varint,9,opt,name=MID2,def=-1" json:"MID2,omitempty"`
	// reserved ID3
	MID3 *int64 `protobuf:"varint,10,opt,name=MID3,def=-1" json:"MID3,omitempty"`
	// reserved Url1
	MUrl1 *string `protobuf:"bytes,11,opt,name=MUrl1" json:"MUrl1,omitempty"`
	// reserved Url2
	MUrl2 *string `protobuf:"bytes,12,opt,name=MUrl2" json:"MUrl2,omitempty"`
	// reserved Url3
	MUrl3                *string  `protobuf:"bytes,13,opt,name=MUrl3" json:"MUrl3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { return }
func (m *Route) String() string { return "" }
func (*Route) ProtoMessage()    { return }
func (*Route) Descriptor() ([]byte, []int) {
	return []byte{}, []int{}
}
func (m *Route) XXX_Unmarshal(b []byte) error {
	return nil
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return []byte{}, nil
}
func (m *Route) XXX_Merge(src proto.Message) {
	return
}
func (m *Route) XXX_Size() int {
	return 0
}
func (m *Route) XXX_DiscardUnknown() {
	return
}

const Default_Route_GID int32 = -1
const Default_Route_UID int32 = -1
const Default_Route_MID1 int64 = -1
const Default_Route_MID2 int64 = -1
const Default_Route_MID3 int64 = -1

func (m *Route) GetSrc() string {
	return ""
}
func (m *Route) GetDst() string {
	return ""
}
func (m *Route) GetRID() int32 {
	return 0
}
func (m *Route) GetIID() int64 {
	return 0
}
func (m *Route) GetPID() int32 {
	return 0
}
func (m *Route) GetGID() int32 {
	return 0
}
func (m *Route) GetUID() int32 {
	return 0
}
func (m *Route) GetMID1() int64 {
	return 0
}
func (m *Route) GetMID2() int64 {
	return 0
}
func (m *Route) GetMID3() int64 {
	return 0
}
func (m *Route) GetMUrl1() string {
	return ""
}
func (m *Route) GetMUrl2() string {
	return ""
}
func (m *Route) GetMUrl3() string {
	return ""
}

// Loop请求（请不要保持对其的引用，随时可能被重置）
type LoopReq struct {
	Route                *Route   `protobuf:"bytes,1,opt,name=Route" json:"Route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoopReq) Reset()         { return }
func (m *LoopReq) String() string { return "" }
func (*LoopReq) ProtoMessage()    { return }
func (*LoopReq) Descriptor() ([]byte, []int) {
	return []byte{}, []int{}
}
func (m *LoopReq) XXX_Unmarshal(b []byte) error {
	return nil
}
func (m *LoopReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return []byte{}, nil
}
func (m *LoopReq) XXX_Merge(src proto.Message) {
	return
}
func (m *LoopReq) XXX_Size() int {
	return 0
}
func (m *LoopReq) XXX_DiscardUnknown() {
	return
}
func (m *LoopReq) GetRoute() *Route {
	return nil
}

// Msg请求（请不要保持对其的引用，随时可能被重置）
type MsgReq struct {
	// 路由
	Route *Route `protobuf:"bytes,1,req,name=Route" json:"Route,omitempty"`
	// 数据包
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgReq) Reset()         { return }
func (m *MsgReq) String() string { return "" }
func (*MsgReq) ProtoMessage()    { return }
func (*MsgReq) Descriptor() ([]byte, []int) {
	return []byte{}, []int{}
}
func (m *MsgReq) XXX_Unmarshal(b []byte) error {
	return nil
}
func (m *MsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return []byte{}, nil
}
func (m *MsgReq) XXX_Merge(src proto.Message) {
	return
}
func (m *MsgReq) XXX_Size() int {
	return 0
}
func (m *MsgReq) XXX_DiscardUnknown() {
	return
}
func (m *MsgReq) GetRoute() *Route {
	return nil
}
func (m *MsgReq) GetData() []byte {
	return []byte{}
}

// Rpc请求（请不要保持对其的引用，随时可能被重置）
type RpcReq struct {
	// 路由
	Route *Route `protobuf:"bytes,1,req,name=Route" json:"Route,omitempty"`
	// 数据包
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcReq) Reset()         { return }
func (m *RpcReq) String() string { return "" }
func (*RpcReq) ProtoMessage()    { return }
func (*RpcReq) Descriptor() ([]byte, []int) {
	return []byte{}, []int{}
}
func (m *RpcReq) XXX_Unmarshal(b []byte) error {
	return nil
}
func (m *RpcReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return []byte{}, nil
}
func (m *RpcReq) XXX_Merge(src proto.Message) {
	return
}
func (m *RpcReq) XXX_Size() int {
	return 0
}
func (m *RpcReq) XXX_DiscardUnknown() {
	return
}
func (m *RpcReq) GetRoute() *Route {
	return nil
}
func (m *RpcReq) GetData() []byte {
	return []byte{}
}

// Rpc响应（请不要保持对其的引用，随时可能被重置）
type RpcResp struct {
	// 路由
	Route *Route `protobuf:"bytes,1,req,name=Route" json:"Route,omitempty"`
	// 数据包
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcResp) Reset()         { return }
func (m *RpcResp) String() string { return "" }
func (*RpcResp) ProtoMessage()    { return }
func (*RpcResp) Descriptor() ([]byte, []int) {
	return []byte{}, []int{}
}
func (m *RpcResp) XXX_Unmarshal(b []byte) error {
	return nil
}
func (m *RpcResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return []byte{}, nil
}
func (m *RpcResp) XXX_Merge(src proto.Message) {
	return
}
func (m *RpcResp) XXX_Size() int {
	return 0
}
func (m *RpcResp) XXX_DiscardUnknown() {
	return
}
func (m *RpcResp) GetRoute() *Route {
	return nil
}
func (m *RpcResp) GetData() []byte {
	return []byte{}
}

// Cgi请求（请不要保持对其的引用，随时可能被重置）
type CgiReq struct {
	// 路由
	Route *Route `protobuf:"bytes,1,req,name=Route" json:"Route,omitempty"`
	// 方法
	Method *string `protobuf:"bytes,2,req,name=Method" json:"Method,omitempty"`
	// 接口
	Path *string `protobuf:"bytes,3,req,name=Path" json:"Path,omitempty"`
	// 路径
	Uri *string `protobuf:"bytes,4,req,name=Uri" json:"Uri,omitempty"`
	// 地址
	Addr *string `protobuf:"bytes,5,req,name=Addr" json:"Addr,omitempty"`
	// 头部
	Header []byte `protobuf:"bytes,6,req,name=Header" json:"Header,omitempty"`
	// 参数
	Query []byte `protobuf:"bytes,7,opt,name=Query" json:"Query,omitempty"`
	// 长度
	Length *int64 `protobuf:"varint,8,req,name=Length" json:"Length,omitempty"`
	// 数据
	Body                 []byte   `protobuf:"bytes,9,opt,name=Body" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CgiReq) Reset()         { return }
func (m *CgiReq) String() string { return "" }
func (*CgiReq) ProtoMessage()    { return }
func (*CgiReq) Descriptor() ([]byte, []int) {
	return []byte{}, []int{}
}
func (m *CgiReq) XXX_Unmarshal(b []byte) error {
	return nil
}
func (m *CgiReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return []byte{}, nil
}
func (m *CgiReq) XXX_Merge(src proto.Message) {
	return
}
func (m *CgiReq) XXX_Size() int {
	return 0
}
func (m *CgiReq) XXX_DiscardUnknown() {
	return
}
func (m *CgiReq) GetRoute() *Route {
	return nil
}
func (m *CgiReq) GetMethod() string {
	return ""
}
func (m *CgiReq) GetPath() string {
	return ""
}
func (m *CgiReq) GetUri() string {
	return ""
}
func (m *CgiReq) GetAddr() string {
	return ""
}
func (m *CgiReq) GetHeader() []byte {
	return []byte{}
}
func (m *CgiReq) GetQuery() []byte {
	return []byte{}
}
func (m *CgiReq) GetLength() int64 {
	return 0
}
func (m *CgiReq) GetBody() []byte {
	return []byte{}
}

// Cgi响应（请不要保持对其的引用，随时可能被重置）
type CgiResp struct {
	// 路由
	Route *Route `protobuf:"bytes,1,req,name=Route" json:"Route,omitempty"`
	// 状态
	Status *int32 `protobuf:"varint,2,opt,name=Status" json:"Status,omitempty"`
	// 返回头部
	Header []byte `protobuf:"bytes,3,opt,name=Header" json:"Header,omitempty"`
	// 长度
	Length *int64 `protobuf:"varint,4,opt,name=Length" json:"Length,omitempty"`
	// 数据
	Body                 []byte   `protobuf:"bytes,5,opt,name=Body" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CgiResp) Reset()         { return }
func (m *CgiResp) String() string { return "" }
func (*CgiResp) ProtoMessage()    { return }
func (*CgiResp) Descriptor() ([]byte, []int) {
	return []byte{}, []int{}
}
func (m *CgiResp) XXX_Unmarshal(b []byte) error {
	return nil
}
func (m *CgiResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return []byte{}, nil
}
func (m *CgiResp) XXX_Merge(src proto.Message) {
	return
}
func (m *CgiResp) XXX_Size() int {
	return 0
}
func (m *CgiResp) XXX_DiscardUnknown() {
	return
}
func (m *CgiResp) GetRoute() *Route {
	return nil
}
func (m *CgiResp) GetStatus() int32 {
	return 0
}
func (m *CgiResp) GetHeader() []byte {
	return []byte{}
}
func (m *CgiResp) GetLength() int64 {
	return 0
}
func (m *CgiResp) GetBody() []byte {
	return []byte{}
}
func init() {
	return
}
func init() { return }
